# GitHub Pages Configuration for Plugin-Wiki
title: Cybernetic Forge Plugin Wiki
description: Documentation and wiki for Cybernetic Forge plugins
baseurl: "/Plugin-Wiki" # the subpath of your site, e.g. /blog
url: "https://cybernetic-forge.github.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - README.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
